import { Roboto, Raleway } from 'next/font/google'

import AppLayout from '@/components/layouts/App'

import '@/styles/globals.css'

const ralewayFont = Raleway({
    weight: 'variable',
    style: ['italic', 'normal'],
    display: 'swap',
    subsets: ['latin'],
    variable: '--open-sans-font',
})
const robotoFont = Roboto({
    subsets: ['latin'],
    weight: ['100', '300', '400', '500', '700', '900'],
    style: ['italic', 'normal'],
    display: 'swap',
    subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={robotoFont.className}>
                <AppLayout>{children}</AppLayout>
            </body>
        </html>
    )
}
